# -*- coding: utf-8 -*-
"""Skin Disease Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bZjqZ7E62_IjtR8K6DeECTZZsShne7H
"""

import os
Home = os.getcwd() #A Home constant is initialized to make it easier for us to manage multiple datasets
print(Home)

!pip install ultralytics #Checks CPU
import ultralytics
import ultralytics
ultralytics.checks()

# Commented out IPython magic to ensure Python compatibility.
!mkdir {Home}/datasets
# %cd {Home}/datasets
# %ls
print(Home)

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="F9FVWzUbzzUqHLca1MP3")
project = rf.workspace("skin-diseases-jzde4").project("skin-diseases-i30ay")
version = project.version(1)
dataset = version.download("yolov11")

!sed -i '$d' {dataset.location}/data.yaml #Delete the last line
!sed -i '$d' {dataset.location}/data.yaml #Delete the second-to-last line
!sed -i '$d' {dataset.location}/data.yaml #Delete the third-to-last line

"""Custom Training"""

!yolo task=detect mode=train model=yolo11s.pt data={dataset.location}/data.yaml epochs=10 imgsz=400 plots=True

from google.colab import files
from IPython.display import Image

from IPython.display import Image as IPyImage
IPyImage(filename=f'{Home}/runs/detect/train/confusion_matrix.png')

